name: Atualizar README

on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r cache/requirements.txt

      - name: Atualizar SVG
        run: python scripts/update_svg.py

      - name: Commitar mudanças
        run: |
          git config --global user.email "faelfernando1408@gmail.com"
          git config --global user.name "07Rafael08"
          git add .
          git commit -m "update: uptime diário" || echo "sem mudanças"
          git push
